spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: lky110408@gmail.com
    password: fuudttdzlmlgqehu
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://portfolio.c4nscvpnlijb.ap-northeast-2.rds.amazonaws.com:3306/joinus
    username: admin
    password: 1q2w3e4r
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 838840591105-lv9u8nsksisbjkkbjsqlmuj62vho7ohs.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          kakao:
            client-id: 2ac4a56f2e916b3da13effc3a4079b04
            client-secret: ZkdJ8QDKCnlZKhSPf68IScwXvEZbWB4s
            redirect-uri: http://3.39.18.64/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
              - account_email
          naver:
            client-id: _dudyQe0NT5vMiLMVBtU
            client-secret: Mn9dSNB_un
            redirect-uri: http://3.39.18.64/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
    
mybatis:
  mapper-locations:
    - /mappers/*.xml
jwt:
  secret: EAGsKy84nn189GWAYJEm585gtSujTSJnsaHFR3fzRLrzmKbdn4bPkOY1jPOfZwTc
  
file:
#  path: /Users/leesfact/workspace/joinus/back_joinus/upload/
#  path: C:/aws_project/workspace/joinus/back_joinus/upload/  #경로 맨끝엔 "/" 넣어준다
  path: /home/ubuntu/upload/
